WordApp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.taskPage, name='taskpage'),
    path('file-upload', views.fileUpload, name='fileUpload')
]

coreApp/urls.py
from django.contrib import admin
from django.urls import path, include
from WordApp import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WordApp.urls'))
]

WordApp/models.py
from django.db import models

# Create your models here.

WordApp/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField()


class QueryForm(forms.Form):
    fileNames = forms.SelectMultiple()
    top = forms.IntegerField()

WordApp/views.py
from collections import Counter
import os

from django.conf import settings
from django.http import HttpResponseRedirect
from django.shortcuts import render
from . import utils
from .forms import UploadFileForm


# Create your views here.
def taskPage(request):
    files = []
    for file in os.listdir(settings.FILE_ROOT):
        if file.endswith(".txt"):
            files.append(file)
    context = {'files': files, 'form': UploadFileForm()}
    if request.method == 'POST':
        fileNames = request.POST.getlist('fileNames')
        top_n = int(request.POST.get('top'))
        result = utils.readFiles(fileNames)
        # context['result'] = result
        word_counter = Counter(result['wordcount'])
        result_table = []
        for word, count in word_counter.most_common(top_n):
            result_table.append(
                {'word': word, 'files': result['in_files'][word], 'sentences': result['in_sentences'][word]})
        context['results'] = result_table
        return render(request, 'taskpage.html', context=context)
    return render(request, 'taskpage.html', context=context)


def fileUpload(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        x = request.FILES['file']
        if form.is_valid():
            utils.handle_uploaded_file(request.FILES['file'])
            return HttpResponseRedirect('/')

WordApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Eigen Test</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
</head>
<body>
<div class="page-header">
    <h1><a href="/">Eigen Test</a></h1>
</div>
<div class="container">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

WordApp/templates/taskpage.html
{% extends 'base.html' %}
{% block content %}

<form action="/" method="post">
    {% csrf_token %}
    <span>Query from files</span>
    <select style="min-width:50%" id="file-select" multiple="multiple" name="fileNames">
        {%for file in files%}
        <option selected value="{{file}}">{{file}}</option>
        {%endfor%}
    </select>
    <span> show top <span>
    <input class="button" type="number" name="top" value="10">
    <input class="button" type="submit" value="Submit">
</form>
<br/>
<h4>or Add more file</h4>
<form action="/file-upload" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="id_file">Add a New File:</label>
    <input type="file" name="file" required="" id="id_file">
    <input class="button" type="submit" value="Submit">
</form>
<table class="table is-strip">
    <thead>
    <th>Word(#)</th>
    <th>Documents</th>
    <th>Sentences containing the word</th>
    </thead>
    {%for each in results%}
    <tr>
        <td>{{each.word}}</td>
        <td>{%for filename in each.files%} {{filename}} {%endfor%}</td>
        <td>
            <div style="max-height:100px; overflow:auto">{%for sentence in each.sentences%}<p>{{sentence}}</p>{%endfor%}
            </div>
        </td>
        {{each.in_sentences}}
    </tr>
    {%endfor%}
</table>
<script>
    $('#file-select').select2()



</script>
{% endblock %}